#include <iostream>
using namespace std;
int main(){
    cout<<"Welcome to Jatin's 4-Wheelers Showroom.I guess you are here for your driving license"<<endl;
    cout<<"first of all we need to check your Eligibility"<<endl;
    int age{};
    cout<<"So here is the eligibility form"<< endl;
    cout<<"1.You must be 18 years old "<<endl;
    cout<<"2. You must have a valid Social Security number"<<endl;
    cout<<"3.You haven't commited any car accident"<<endl;
    cout<<"Note:-Some special Eligibility offers we generated by Government of India under consideration that Students above 15 years of age can also be given Driving license but on parents consent"<<endl;
    cout<<"You need to Enter your age :";
    cin>>age;
    bool parents_consent{};
    bool ssn{};
    bool accidents{};

    cout<<"If there is parents consent enter 1 otherwise 0 ";
    cin>>parents_consent;

    cout<<"Enter 1 if you have Social Security Number ";
    cin>>ssn;

    cout<<"Enter 1 if you never commit car accidents ";
    cin>>accidents;

    bool eligibility;
    eligibility = ((age>=18 && ssn==1 && accidents==1) || (age>15 && ssn==1 && accidents==1 && parents_consent==1) );

    
    cout<<boolalpha;
    cout<<"true means that you are eligible for driving license and false means the opposite "<<eligibility<<endl;


}